name: Windows Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: "Windows MSVC"
            os: windows-latest
            cc: "cl"
            cxx: "cl"
            build_type: "Release"
            environment_script: '"C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"'
          - name: "Windows MinGW"
            os: windows-latest
            cc: "gcc"
            cxx: "g++"
            build_type: "Release"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies (CMake, Ninja)
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --yes
        choco install ninja --yes

    - name: Configure build
      shell: cmd
      run: |
        call ${{ matrix.environment_script }}
        cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_C_COMPILER=${{ matrix.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.cxx }}

    - name: Build
      shell: cmd
      run: |
        call ${{ matrix.environment_script }}
        cmake --build build
